version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: competeart-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: competeart
      POSTGRES_PASSWORD: competeart
      POSTGRES_DB: competeart
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
